export * from "@/pages/dashboard/home";
export * from "@/pages/dashboard/employee";
export * from "@/pages/dashboard/warehouse";
export * from "@/pages/dashboard/product";
export * from "@/pages/dashboard/receipt";
export * from "@/pages/dashboard/partner";
export * from "@/pages/dashboard/stock";
export * from "@/pages/dashboard/order";
export * from "@/pages/dashboard/customer"